give  Thu 25 Mar 12:21:56 AEDT 2021: passes 14 autotests, need to work on girt-rm

diff --git a/girt-show-og b/girt-show-og
--- a/girt-show-og
+++ b/girt-show-og
@@ -52,7 +52,8 @@ else
 			#check if file is within previous commit folder
 			if test -e .girt/.commit/$commit/$filename
 			then
-				:
+				echo "girt-show: error: '$filename' not found in commit '$commit'"
+				#exit 1
 			else
 				cat .girt/.commit/$filename
 				exit 1
